<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bones.Tests\Bones.Tests.csproj" />
    <ProjectReference Include="..\Bones.Akka\Bones.Akka.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.14" />
    <PackageReference Include="Akka.DependencyInjection" Version="1.5.14" />
    <PackageReference Include="Akka.TestKit" Version="1.5.14" />
    <PackageReference Include="Akka.TestKit.Xunit" Version="1.5.14" />
  </ItemGroup>

</Project>
