variables:
  GIT_SSL_NO_VERIFY: "true"

  DIR_TESTS: UnitTest

stages:
  - test

test:
  stage: test
  script:
  - cd $DIR_TESTS
  - for d in *.Tests/ ; do dotnet test $d; done
  image: microsoft/dotnet:2.2-sdk