<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageOutputPath>./nugets</PackageOutputPath>
    <Version>$(VERSION)</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fody" Version="6.8.2" PrivateAssets="none" />
    <PackageReference Include="FodyPackaging" Version="6.8.2" PrivateAssets="All" />
  </ItemGroup>
</Project>
