version: "3"

services:
  tests:
    build: 
      context: ..
      dockerfile: dev/dockerfiles/tests-dotnet.dockerfile
    networks:
      - bones
  
  tests-ui:
    build: 
      context: ..
      dockerfile: dev/dockerfiles/tests-ui.dockerfile
    networks:
      - bones

networks:
  bones: