<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.62" />
    <ProjectReference Include="..\..\..\..\src\Bones.Flow\Bones.Flow.csproj" />
  </ItemGroup>

</Project>
