name: pipeline

on: [push]

jobs:
  build_and_test:
    name: Build & Test
    uses: ./.github/workflows/build-and-tests.yml

  publish_npm:
    name: Publish NPM
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/publish-to-npm.yml
    secrets: inherit

  publish_nuget:
    name: Publish Nuget
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/publish-to-nuget.yml
    secrets: inherit

  publish_weavers:
    name: Publish weavers
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/publish-weavers.yml
    secrets: inherit
