name: Publish Package to NPM

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - "src/Bones.UI"

    steps:
      # Checking out repository
      - uses: actions/checkout@v3

      # Setting .npmrc file up to publish to npm
      - name: Setting things up 🔧
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          # User or organization
          scope: "@dative-gpi"

      # Publishing with tag name as version
      - name: Publishing to npm 🚀
        run: |
          cd ${{ matrix.folder}}
          yarn
          yarn version --new-version ${{ github.ref_name }} --no-git-tag-version
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
